# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y make linux-headers-$(uname -r)
    cd /vagrant
    sudo -i
    make
  SHELL
end
