# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/jurrml64"
  pbasvt.iz.cebivfvba "furyy", vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l znxr yvahk-urnqref-$(hanzr -e)
    pq /intenag
    fhqb -v
    znxr
  FURYY
raq
