# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/jurrml64"
  pbasvt.iz.cebivqre "iveghnyobk" qb |i|
    i.zrzbel = 1024
    i.pchf = 4
  raq
  pbasvt.iz.cebivfvba "furyy", cevivyrtrq: snyfr, vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l tpp znxr tvg
    tvg pybar --qrcgu 1 tvg://tvg.xreary.bet/cho/fpz/yvahk/xreary/tvg/gbeinyqf/yvahk.tvg
    pq yvahk
    tvg erzbgr nqq yvahk-arkg uggcf://tvg.xreary.bet/cho/fpz/yvahk/xreary/tvg/arkg/yvahk-arkg.tvg
    tvg srgpu yvahk-arkg
    tvg srgpu --gntf yvahk-arkg
    tvg purpxbhg arkg-20160928
    znxr qrspbasvt
    znxr -w5
    fhqb znxr -w5 zbqhyrf_vafgnyy vafgnyy
    fhqb hcqngr-teho2
    fhqb erobbg
  FURYY
raq
