# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get install -y gcc make git
    git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    cd linux
    git remote add linux-next https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
    git fetch linux-next
    git fetch --tags linux-next
    git checkout next-20160928
    make defconfig
    make -j5
    sudo make -j5 modules_install install
    sudo update-grub2
    sudo reboot
  SHELL
end
