# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get install -y make linux-headers-$(uname -r)
    cd /vagrant
    make
  SHELL
  config.vm.provision "shell", privileged: false, path: './tests.sh'
end
