# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y gcc make git
    git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    cd linux
    sudo make defconfig
    echo "CONFIG_LOCALVERSION_AUTO=y" >> .config
    sudo make -j5 LOCALVERSION="-edptla-t02"
    sudo make -j5 modules_install install
    sudo update-grub2
  SHELL
end
