bow-z += gnfx19.b
# Ranoyr QROHT zrffntrf fb jr pna frr bhgchg bs ce_qroht pnyy
PSYNTF_gnfx19.b := -QQROHT

XQVE ?= /yvo/zbqhyrf/$(furyy hanzr -e)/ohvyq

nyy:
	znxr -P $(XQVE) Z=$(CJQ) zbqhyrf

pyrna:
	znxr -P $(XQVE) Z=$(CJQ) pyrna
