# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/wrffvr64"
  pbasvt.iz.cebivqre "iveghnyobk" qb |i|
    i.zrzbel = 1024
    i.pchf = 4
  raq
  pbasvt.iz.cebivfvba "furyy", cevivyrtrq: snyfr, vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l tpp znxr tvg yvahk-fbhepr ivz
    fhqb gne ks /hfe/fep/yvahk-fbhepr-*
  FURYY
raq
