# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
    # I'm going to be modifying the driver for the RTL 8187
    # Configure VirtualBox to filter this device through to the VM
    v.customize ["modifyvm", :id, "--usb", "on"]
    v.customize ["modifyvm", :id, "--usbehci", "on"]
    v.customize ["usbfilter", "add", "0", 
                 "--target", :id, 
                 "--name", "Manufacturer_Realtek_RTL8187_ RTL8187_Wireless [0100]",
                 "--manufacturer", "Manufacturer_Realtek_RTL8187_",
                 "--product", "RTL8187_Wireless"]
  end
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    KERNEL_VERSION=3.16
    apt-get install -y gcc make git linux-source linux-headers-amd64 vim
    tar -C /usr/src/ -xf /usr/src/linux-source-${KERNEL_VERSION}.*
    cd /usr/src/linux-source-${KERNEL_VERSION}
    patch -p1 < /vagrant/0001-Add-eudyptula-id-attribute-to-rtl8187-driver.patch
    ln -s /usr/src/linux-source-${KERNEL_VERSION}/drivers /usr/src/linux-headers-$(uname -r)/
    printf "\n\n" | make oldconfig
    make modules_prepare 
    cd drivers/net/wireless/rtl818x/rtl8187
    make -C /lib/modules/$(uname -r)/build M=$(pwd)
    rmmod rtl8187
    insmod ./rtl8187.ko
    /vagrant/tests.sh
  SHELL
end
