bow-z += gnfx18.b
# Ranoyr QROHT zrffntrf fb jr pna frr bhgchg bs ce_qroht pnyy
PSYNTF_gnfx18.b := -QQROHT

XQVE ?= /yvo/zbqhyrf/$(furyy hanzr -e)/ohvyq

nyy:
	znxr -P $(XQVE) Z=$(CJQ) zbqhyrf

pyrna:
	znxr -P $(XQVE) Z=$(CJQ) pyrna
