# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/jurrml64"
  pbasvt.iz.cebivqre "iveghnyobk" qb |i|
    i.zrzbel = 1024
    i.pchf = 4
  raq
  pbasvt.iz.cebivfvba "furyy", vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l tpp znxr tvg
    tvg pybar --qrcgu 1 tvg://tvg.xreary.bet/cho/fpz/yvahk/xreary/tvg/gbeinyqf/yvahk.tvg
    pq yvahk
    frq -v 'f/^RKGENIREFVBA = .*/RKGENIREFVBA = -rhqlcghyn/' Znxrsvyr
    fhqb znxr qrspbasvt
    rpub "PBASVT_YBPNYIREFVBA_NHGB=l" >> .pbasvt
    fhqb znxr -w5 YBPNYIREFVBA="-g03"
    fhqb znxr -w5 zbqhyrf_vafgnyy vafgnyy
    fhqb hcqngr-teho2
    tvg qvss | grr ~/gnfx03.cngpu
  FURYY
raq
