# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/jurrml64"
  pbasvt.iz.cebivqre "iveghnyobk" qb |i|
    i.zrzbel = 1024
    i.pchf = 4
  raq
  pbasvt.iz.cebivfvba "furyy", vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l tpp znxr tvg
    tvg pybar --qrcgu 1 tvg://tvg.xreary.bet/cho/fpz/yvahk/xreary/tvg/gbeinyqf/yvahk.tvg
    yvahk/fpevcgf/purpxcngpu.cy --ab-gerr -s /intenag/gnfx01.p
    yvahk/fpevcgf/purpxcngpu.cy --ab-gerr -s /intenag/pbqvat_fglyr.p
  FURYY
raq
