# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--usb", "on"]
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y make linux-headers-$(uname -r)
    cd /vagrant
    sudo -i
    make
    sudo depmod /vagrant/task05.ko
    echo "Module created and loaded into module map. Insert a USB keyboard and then check dmesg for the \"Hello World\" message."
  SHELL
end
