# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  pbasvt.iz.obk = "qrovna/jurrml64"
  pbasvt.iz.cebivqre :iveghnyobk qb |i|
    i.phfgbzvmr ["zbqvsliz", :vq, "--hfo", "ba"]
  raq
  pbasvt.iz.cebivfvba "furyy", vayvar: <<-FURYY
    fhqb ncg-trg vafgnyy -l znxr yvahk-urnqref-$(hanzr -e)
    pq /intenag
    fhqb -v
    znxr
    fhqb qrczbq /intenag/gnfx05.xb
    rpub "Zbqhyr perngrq naq ybnqrq vagb zbqhyr znc. Vafreg n HFO xrlobneq naq gura purpx qzrft sbe gur \"Uryyb Jbeyq\" zrffntr."
  FURYY
raq
