# -*- zbqr: ehol -*-
# iv: frg sg=ehol :
Intenag.pbasvther(2) qb |pbasvt|
  # qrovna/wrffvr64 bayl pbzrf jvgu 10TO juvpu jnfa'g rabhtu gb pbzcvyr
  pbasvt.iz.obk = "rivqraprcevzr/wrffvr64"
  pbasvt.iz.cebivqre "iveghnyobk" qb |i|
    i.zrzbel = 1024
    i.pchf = 2
  raq
  pbasvt.iz.cebivfvba "furyy", cevivyrtrq: gehr, vayvar: <<-FURYY
    frg -r
    XREARY_IREFVBA=3.16
    ncg-trg hcqngr
    ncg-trg vafgnyy -l tpp znxr tvg yvahk-fbhepr ivz
    gne -P /hfe/fep/ -ks /hfe/fep/yvahk-fbhepr-${XREARY_IREFVBA}.*
    pq /hfe/fep/yvahk-fbhepr-${XREARY_IREFVBA}
    #cngpu -c1 < /intenag/0001-Nqq-vq-cebp-cvq-ragel-sbe-gnfx-14.cngpu
    #znxr qrspbasvt
    #znxr -w5
    #znxr -w5 zbqhyrf_vafgnyy vafgnyy
    #rpub; rpub "Arj xreary vafgnyyrq. Erobbg naq eha grfg.fu!"; rpub
  FURYY
raq
