# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  # debian/jessie64 only comes with 10GB which wasn't enough to compile
  config.vm.box = "evidenceprime/jessie64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    set -e
    KERNEL_VERSION=3.16
    apt-get update
    apt-get install -y gcc make git linux-source vim

    # Compile our test program
    cd ~vagrant
    gcc -o task15 /vagrant/task15.c
    chmod +x task15

    # Extract, patch, and install kernel
    tar -C /usr/src/ -xf /usr/src/linux-source-${KERNEL_VERSION}.*
    cd /usr/src/linux-source-${KERNEL_VERSION}
    patch -p1 < /vagrant/0001-Add-sys_eudyptula-syscall-for-task-15.patch
    make defconfig
    make -j5
    make -j5 modules_install install
    echo; echo "New kernel installed. Reboot and run ./task15!"; echo
  SHELL
end
